version: "3.8"

services:

  express:
    container_name: express
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    image: express:latest
    restart: unless-stopped
